### ISSUE TITLE
GEJobRunner crash with job not found (KeyError) when updating grace period

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/genomics#89]
Bug in the `GEJobRunner` class (originally reported here https://github.com/fls-bioinformatics-core/auto_process_ngs/issues/320):

    Traceback (most recent call last):
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/bin/run_qc.py", line 209, in <module>
        'report_runner': report_runner,
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/auto_process_ngs/qc/pipeline.py", line 339, in run
        verbose=verbose)
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/auto_process_ngs/pipeliner.py", line 1473, in run
        if task.updated:
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/auto_process_ngs/pipeliner.py", line 1653, in updated
        njobs,ncompleted = self.njobs()
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/auto_process_ngs/pipeliner.py", line 1991, in njobs
        if job.completed:
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/auto_process_ngs/simple_scheduler.py", line 815, in completed
        return ((not self.is_running) and (self.end_time is not None))
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/auto-process-ngs/ICELL8-scATAC-seq/auto_process_ngs/simple_scheduler.py", line 795, in is_running
        return self.isRunning()
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/genomics-bcftbx/devel/bcftbx/Pipeline.py", line 216, in isRunning
        self.update()
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/genomics-bcftbx/devel/bcftbx/Pipeline.py", line 244, in update
        if not self.__runner.isRunning(self.job_id):
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/genomics-bcftbx/devel/bcftbx/JobRunner.py", line 143, in isRunning
        return job_id in self.list()
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/genomics-bcftbx/devel/bcftbx/JobRunner.py", line 710, in list
        self.__update_job_grace_period(job_id)
      File "/mnt/fls01-bcf01/software/csf3/bcf/apps/genomics-bcftbx/devel/bcftbx/JobRunner.py", line 804, in __update_job_grace_period
        if ((time.time() - self.__start_time[job_id]) >
    KeyError: '358215'

**Comment by pjbriggs** [comment]
Should be addressed by PRs #90 and #91.
